[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "codi"
dynamic = ["version"]
dependencies = [
  "numpy",
  "Pillow",
  "matplotlib",
]

[tool.setuptools.packages.find]
where = ["src"]
